function [] =  Nyquist_plot(HTM_evals, nfm, De, Z, gamma0, omega)

%This function reshape the HTM structure to generate a continuos Nyquist
%plot using a specific number of evals. This function generate two Nyquist
%plots. The first plot is generated by the evals from the HTM without previos re-ordering.
% For the second plot, we order the evals based on their evecs similarity before we generate the plot 



%% Ordering eigenvalues based on proximity

% ordered_evals= evals_ordering (HTM_evals, HTM_evecs); 

% k = find(omega == 0);
% HTM_evals = sortrows(HTM_evals, k, 'descend' );

ordered_evals= evals_ordering (HTM_evals); 
evals_real = real(ordered_evals);
evals_imag = imag(ordered_evals);


[nrows, ~] = size(ordered_evals);

%Ordered Eigenspectrum
for n =1:nrows
plot(evals_real (n,:), evals_imag (n, :), 'o')
hold on
% plot(evals_real (n, 1:index), evals_imag (n, 1:index),  'LineStyle', 'none','Marker','x')
plot(0,0,'+', MarkerSize=10, MarkerFaceColor='r')
end
xlabel('$\mathrm{Re}(\lambda)$', 'Interpreter', 'latex')
ylabel('$\mathrm{Im}(\lambda)$', 'Interpreter', 'latex')
legend ('Z = '+string(Z))
legend box off
end 
